language: python
python:
  - "3.4"

# command to install dependencies
install: "pip install -r requirements/development.txt"

# command to run tests
script: python manage.py test --settings=quotations.settings.development --with-coverage && flake8

# coverage!
after_success:
    coveralls
