language: python
python:
  - "3.4"

# command to install dependencies
install: "pip install -r requirements/development.txt"

# command to run tests
script:
    - coverage run manage.py test quotations --settings=quotations.settings.development
    - flake8

# coverage!
after_success:
    coveralls
